image: Visual Studio 2019
init:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
configuration: Debug
platform: x86
before_build:
  - dotnet restore
build:
  parallel: true
  project: ViruZLauncher.sln
test:
  assemblies:
    only:
      - ViruZLauncher.Tests.dll